self-hosted-runner:
  labels:
    - arm64
    - large
    - large-arm64
    - large-arm64-metal
    - small
    - small-arm64
    - us-east-2
config-variables:
  - BENCHMARK_PROJECT_ID_PUB
  - BENCHMARK_PROJECT_ID_SUB
  - REMOTE_STORAGE_AZURE_CONTAINER
  - REMOTE_STORAGE_AZURE_REGION
  - SLACK_UPCOMING_RELEASE_CHANNEL_ID
  - DEV_AWS_OIDC_ROLE_ARN
