# based on build-tools but adds postgresql-client and postgresql packages
ARG BUILD_TOOLS_BASE_IMAGE

FROM ${BUILD_TOOLS_BASE_IMAGE}

# Switch to root user
USER root

# postgresql (depends on  curl)
# needed in some tests because neon artifacts cannot be used 
# in combination with staticaclly built openssl
# due to https://github.com/neondatabase/neon/issues/8275
ENV PG_VERSION=16
RUN set -e \
    && curl -fsSL 'https://www.postgresql.org/media/keys/ACCC4CF8.asc' | apt-key add - \
    && echo 'deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
    && apt update \
    && apt install -y postgresql-${PG_VERSION} \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Switch back to nonroot user
USER nonroot:nonroot
WORKDIR /home/nonroot

