[pytest]
filterwarnings =
    error::pytest.PytestUnhandledThreadExceptionWarning
    error::UserWarning
    ignore:record_property is incompatible with junit_family:pytest.PytestWarning
addopts =
    -m 'not remote_cluster'
    --ignore=test_runner/performance
markers =
    remote_cluster
testpaths =
    test_runner
minversion = 6.0
log_format = %(asctime)s.%(msecs)-3d %(levelname)s [%(filename)s:%(lineno)d] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli = true
timeout = 300
