# Helm chart values for neon-proxy-link.
# This is a YAML-formatted file.

image:
  repository: neondatabase/neon

settings:
  authBackend: "link"
  authEndpoint: "https://console.stage.neon.tech/authenticate_proxy_request/"
  uri: "https://console.stage.neon.tech/psql_session/"
  sentryEnvironment: "development"

# -- Additional labels for neon-proxy-link pods
podLabels:
  zenith_service: proxy
  zenith_env: dev
  zenith_region: us-east-2
  zenith_region_slug: us-east-2

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    external-dns.alpha.kubernetes.io/hostname: neon-proxy-link-mgmt.beta.us-east-2.aws.neon.build

exposedService:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: neon-proxy-link.beta.us-east-2.aws.neon.build

#metrics:
#  enabled: true
#  serviceMonitor:
#    enabled: true
#    selector:
#      release: kube-prometheus-stack

extraManifests:
  - apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMServiceScrape
    metadata:
      name: "{{ include \"neon-proxy.fullname\" . }}"
      labels:
        helm.sh/chart: neon-proxy-{{ .Chart.Version }}
        app.kubernetes.io/name: neon-proxy
        app.kubernetes.io/instance: "{{ include \"neon-proxy.fullname\" . }}"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/managed-by: Helm
      namespace: "{{ .Release.Namespace }}"
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: "neon-proxy"
      endpoints:
        - port: http
          path: /metrics
          interval: 10s
          scrapeTimeout: 10s
      namespaceSelector:
        matchNames:
          - "{{ .Release.Namespace }}"
