fullnameOverride: "neon-stress-proxy-scram"

settings:
  authBackend: "console"
  authEndpoint: "http://neon-stress-console.local/management/api/v2"
  domain: "*.stress.neon.tech"
  sentryEnvironment: "development"

podLabels:
  zenith_service: proxy-scram
  zenith_env: staging
  zenith_region: eu-west-1
  zenith_region_slug: ireland

exposedService:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: '*.stress.neon.tech'

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    selector:
      release: kube-prometheus-stack

extraManifests:
  - apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMServiceScrape
    metadata:
      name: "{{ include \"neon-proxy.fullname\" . }}"
      labels:
        helm.sh/chart: neon-proxy-{{ .Chart.Version }}
        app.kubernetes.io/name: neon-proxy
        app.kubernetes.io/instance: "{{ include \"neon-proxy.fullname\" . }}"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/managed-by: Helm
      namespace: "{{ .Release.Namespace }}"
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: "neon-proxy"
      endpoints:
        - port: http
          path: /metrics
          interval: 10s
          scrapeTimeout: 10s
      namespaceSelector:
        matchNames:
          - "{{ .Release.Namespace }}"
