useCertManager: true

replicaCount: 3

image:
  tag: "3113"

exposedService:
  # exposedService.port -- Exposed Service proxy port
  port: 4432
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.snirouter.theta.us-east-1.internal.aws.neon.tech"

settings:
  domain: "*.snirouter.theta.us-east-1.internal.aws.neon.tech"

imagePullSecrets:
  - name: docker-hub-neon

metrics:
  enabled: false
