from .exceptions import FrameDataMissingError as FrameDataMissingError, FrameTooLargeError as FrameTooLargeError, ProtocolError as ProtocolError
from hyperframe.frame import Frame

CONTINUATION_BACKLOG: int

class FrameBuffer:
    data: bytes
    max_frame_size: int
    def __init__(self, server: bool = False) -> None: ...
    def add_data(self, data: bytes) -> None: ...
    def __iter__(self) -> FrameBuffer: ...
    def __next__(self) -> Frame: ...
