from typing import NamedTuple

from _typeshed import Incomplete

from .exceptions import FlowControlError as FlowControlError
from .exceptions import ProtocolError as ProtocolError

UPPER_RE: Incomplete
CONNECTION_HEADERS: Incomplete

def extract_method_header(headers): ...
def is_informational_response(headers): ...
def guard_increment_window(current, increment): ...
def authority_from_headers(headers): ...

class HeaderValidationFlags(NamedTuple):
    is_client: Incomplete
    is_trailer: Incomplete
    is_response_header: Incomplete
    is_push_promise: Incomplete

def validate_headers(headers, hdr_validation_flags): ...
def normalize_outbound_headers(headers, hdr_validation_flags): ...
def normalize_inbound_headers(headers, hdr_validation_flags): ...
def validate_outbound_headers(headers, hdr_validation_flags): ...
