from .exceptions import FlowControlError as FlowControlError
from _typeshed import Incomplete

LARGEST_FLOW_CONTROL_WINDOW: Incomplete

class WindowManager:
    max_window_size: Incomplete
    current_window_size: Incomplete
    def __init__(self, max_window_size: int) -> None: ...
    def window_consumed(self, size: int) -> None: ...
    def window_opened(self, size: int) -> None: ...
    def process_bytes(self, size: int) -> int | None: ...
