#!/usr/bin/env bash

# This is a helper script for setting up/updating our python environment.
# It is intended to be a primary endpoint for all the people who want to
# just setup test environment without going into details of python package management

poetry config --list

if [ -z "${CI}" ]; then
    poetry install --no-root --no-interaction --ansi
else
    poetry install --no-root
fi
