#!/usr/bin/env bash

set -euox pipefail

# Runs all formatting tools to ensure the project is up to date
echo 'Reformatting Rust code'
cargo fmt
echo 'Reformatting Python code'
poetry run isort test_runner scripts
poetry run flake8 test_runner scripts
poetry run black test_runner scripts
