{
  collector_name: 'neon_collector',
  metrics: [
    import 'sql_exporter/checkpoints_req.libsonnet',
    import 'sql_exporter/checkpoints_timed.libsonnet',
    import 'sql_exporter/compute_backpressure_throttling_seconds.libsonnet',
    import 'sql_exporter/compute_current_lsn.libsonnet',
    import 'sql_exporter/compute_logical_snapshot_files.libsonnet',
    import 'sql_exporter/compute_logical_snapshots_bytes.libsonnet',
    import 'sql_exporter/compute_max_connections.libsonnet',
    import 'sql_exporter/compute_receive_lsn.libsonnet',
    import 'sql_exporter/compute_subscriptions_count.libsonnet',
    import 'sql_exporter/connection_counts.libsonnet',
    import 'sql_exporter/db_total_size.libsonnet',
    import 'sql_exporter/file_cache_read_wait_seconds_bucket.libsonnet',
    import 'sql_exporter/file_cache_read_wait_seconds_count.libsonnet',
    import 'sql_exporter/file_cache_read_wait_seconds_sum.libsonnet',
    import 'sql_exporter/file_cache_write_wait_seconds_bucket.libsonnet',
    import 'sql_exporter/file_cache_write_wait_seconds_count.libsonnet',
    import 'sql_exporter/file_cache_write_wait_seconds_sum.libsonnet',
    import 'sql_exporter/getpage_prefetch_discards_total.libsonnet',
    import 'sql_exporter/getpage_prefetch_misses_total.libsonnet',
    import 'sql_exporter/getpage_prefetch_requests_total.libsonnet',
    import 'sql_exporter/getpage_prefetches_buffered.libsonnet',
    import 'sql_exporter/getpage_sync_requests_total.libsonnet',
    import 'sql_exporter/getpage_wait_seconds_bucket.libsonnet',
    import 'sql_exporter/getpage_wait_seconds_count.libsonnet',
    import 'sql_exporter/getpage_wait_seconds_sum.libsonnet',
    import 'sql_exporter/lfc_approximate_working_set_size.libsonnet',
    import 'sql_exporter/lfc_approximate_working_set_size_windows.libsonnet',
    import 'sql_exporter/lfc_cache_size_limit.libsonnet',
    import 'sql_exporter/lfc_hits.libsonnet',
    import 'sql_exporter/lfc_misses.libsonnet',
    import 'sql_exporter/lfc_used.libsonnet',
    import 'sql_exporter/lfc_writes.libsonnet',
    import 'sql_exporter/logical_slot_restart_lsn.libsonnet',
    import 'sql_exporter/max_cluster_size.libsonnet',
    import 'sql_exporter/pageserver_disconnects_total.libsonnet',
    import 'sql_exporter/pageserver_requests_sent_total.libsonnet',
    import 'sql_exporter/pageserver_send_flushes_total.libsonnet',
    import 'sql_exporter/pageserver_open_requests.libsonnet',
    import 'sql_exporter/pg_stats_userdb.libsonnet',
    import 'sql_exporter/replication_delay_bytes.libsonnet',
    import 'sql_exporter/replication_delay_seconds.libsonnet',
    import 'sql_exporter/retained_wal.libsonnet',
    import 'sql_exporter/wal_is_lost.libsonnet',
  ],
  queries: [
    {
      query_name: 'neon_perf_counters',
      query: importstr 'sql_exporter/neon_perf_counters.sql',
    },
  ],
}
