storage:
  vars:
    bucket_name: neon-prod-storage-us-east-2
    bucket_region: us-east-2
    console_mgmt_base_url: http://console-release.local
    broker_endpoint: https://storage-broker.delta.us-east-2.internal.aws.neon.tech:443
    pageserver_config_stub:
      pg_distrib_dir: /usr/local
      remote_storage:
        bucket_name: "{{ bucket_name }}"
        bucket_region: "{{ bucket_region }}"
        prefix_in_bucket: "pageserver/v1"
    safekeeper_s3_prefix: safekeeper/v1/wal
    hostname_suffix: ""
    remote_user: ssm-user
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_bucket_name: neon-prod-storage-us-east-2
    console_region_id: aws-us-east-2

  children:
    pageservers:
      hosts:
        pageserver-0.us-east-2.aws.neon.tech:
          ansible_host:  i-062227ba7f119eb8c
        pageserver-1.us-east-2.aws.neon.tech:
          ansible_host:  i-0b3ec0afab5968938

    safekeepers:
      hosts:
        safekeeper-0.us-east-2.aws.neon.tech:
          ansible_host:  i-0e94224750c57d346
        safekeeper-1.us-east-2.aws.neon.tech:
          ansible_host:  i-06d113fb73bfddeb0
        safekeeper-2.us-east-2.aws.neon.tech:
          ansible_host:  i-09f66c8e04afff2e8
          
