//! This crate provides the Pageserver's page API. It contains:
//!
//! * proto/page_service.proto: the Protobuf schema for the page API.
//! * proto: auto-generated Protobuf types for gRPC.
//!
//! This crate is used by both the client and the server. Try to keep it slim.

// Code generated by protobuf.
pub mod proto {
    tonic::include_proto!("page_service");

    pub use page_service_client::PageServiceClient;
    pub use page_service_server::{PageService, PageServiceServer};
}
