//! This crate provides the Pageserver's page API. It contains:
//!
//! * proto: auto-generated Protobuf types for gRPC.
//! * model: canonical domain types. Protobuf types are converted into these.
//!
//! See `proto/page_service.proto` for the protocol spec.
//!
//! This crate is used by both the client and the server. Try to keep it slim.
//!

pub mod model;

// Code generated by protobuf.
pub mod proto {
    tonic::include_proto!("page_service");

    pub use page_service_client::PageServiceClient;
    pub use page_service_server::PageServiceServer;
}
