//! This crate has two modules related to the Pageserver Data API:
//!
//! proto: code auto-generated from the protobuf definition
//! model: slightly more ergonomic structs representing the same API
//!
//! See protobuf spec under the protos/ subdirectory.
//!
//! This crate is used by both the client and the server. Try to keep it slim.
//!
pub mod model;

// Code generated by protobuf.
pub mod proto {
    tonic::include_proto!("page_service");
}

pub use proto::page_service_client as client;
