name: Regenerate Postgres Settings

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - pgxn/neon/**.c
      - vendor/postgres-v*
      - vendor/revisions.json

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  regenerate-pg-settings:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Add comment
        uses: thollander/actions-comment-pull-request@65f9e5c9a1f2cd378bd74b2e057c9736982a8e74 # v3
        with:
          comment-tag: ${{ github.job }}
          pr-number: ${{ github.event.number }}
          message: |
            If this PR added a GUC in the Postgres fork or `neon` extension,
            please regenerate the Postgres settings in the `cloud` repo:

            ```
            make NEON_WORKDIR=path/to/neon/checkout \
              -C goapp/internal/shareddomain/postgres generate
            ```

            If you're an external contributor, a Neon employee will assist in
            making sure this step is done.
